### ISSUE TITLE
Make README clear that you need to run rethinkdb 

### ISSUE THREAD

**Issue by mbbroberg** [dalanmiller/rethinkdb-workshop#4]
Running through the instructions, I install everything and error on the server run: 

```
$ npm run dev

> rethink-chat@1.0.0 dev /Users/basho/Documents/Develop/rethinkdb-workshop
> ./node_modules/nodemon/bin/nodemon.js --watch ./server server

15 Oct 18:41:07 - [nodemon] 1.7.1
15 Oct 18:41:07 - [nodemon] to restart at any time, enter `rs`
15 Oct 18:41:07 - [nodemon] watching: /Users/basho/Documents/Develop/rethinkdb-workshop/server/**/*
15 Oct 18:41:07 - [nodemon] starting `node server`
Unhandled rejection RqlDriverError: Could not connect to localhost:28015.
connect ECONNREFUSED 127.0.0.1:28015
    at new RqlDriverError (/Users/basho/Documents/Develop/rethinkdb-workshop/node_modules/rethinkdb/errors.js:14:13)
    at TcpConnection.<anonymous> (/Users/basho/Documents/Develop/rethinkdb-workshop/node_modules/rethinkdb/net.js:77:27)
    at TcpConnection.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at TcpConnection.emit (events.js:169:7)
    at Socket.<anonymous> (/Users/basho/Documents/Develop/rethinkdb-workshop/node_modules/rethinkdb/net.js:510:22)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1250:8)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)


^C
```

If I run `rethinkdb`, it connects just fine: 

```
$  rethinkdb &
[1] 99402
Running rethinkdb 2.1.5-2 (CLANG 7.0.0 (clang-700.0.72))...
Running on Darwin 15.0.0 x86_64
Loading data from directory /Users/basho/Documents/Develop/rethinkdb-workshop/rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on addresses: 127.0.0.1, ::1
To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.
Server ready, "Basho_7ds" 78bf9dd0-2fa7-4399-b152-cf3dbb146d57
 ⚙  ~/Documents/Develop/rethinkdb-workshop   master  npm run dev

> rethink-chat@1.0.0 dev /Users/basho/Documents/Develop/rethinkdb-workshop
> ./node_modules/nodemon/bin/nodemon.js --watch ./server server

15 Oct 18:54:16 - [nodemon] 1.7.1
15 Oct 18:54:16 - [nodemon] to restart at any time, enter `rs`
15 Oct 18:54:16 - [nodemon] watching: /Users/basho/Documents/Develop/rethinkdb-workshop/server/**/*
15 Oct 18:54:16 - [nodemon] starting `node server`
```

I'm not sure how you'd recommend running it, but I'm glad to open a PR for it.

**Comment by dalanmiller** [comment]
Thank you @mjbrender! Fixed - 75ef373c479
